# Generated by Django 3.1.7 on 2021-04-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_domain', models.CharField(blank=True, max_length=20, null=True)),
                ('company_slug', models.SlugField(blank=True, null=True)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company_email_cc', models.EmailField(blank=True, max_length=254, null=True)),
                ('company_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('company_RC', models.CharField(blank=True, max_length=20, null=True)),
                ('company_registered_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
