# Generated by Django 3.1.7 on 2021-04-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_host',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
